### ISSUE TITLE
ask about Saga

### ISSUE THREAD

**Issue by fizz12344321** [dogaanismail/food-ordering-system#1]
Hi, i am reading your project and I love it. But i have a question, what queue do you use for the message queue, how do you manage the state of each service and how do you tackle and implement "Transaction outbox ". Thank u so much

**Comment by dogaanismail** [comment]
Hello,

Thank you so much first of all.

I took a course on Udemy website. I have been watching this and while I am watching it, I am implementing the code blocks. 
So, I strong suggest you to take this course. It is really amazing.
I will implement Transaction outbox pattern later. I do not have much time to watch the course.

Here is the course link. You can find it below.
https://www.udemy.com/course/microservices-clean-architecture-ddd-saga-outbox-kafka-kubernetes/

**Comment by dogaanismail** [comment]
@fizz12344321 Hello!

I am closing the issue. If you have any question, feel free to ask it!
